name: Conurbation
main: me.daddychurchill.Conurbation.Conurbation
version: 0.02
load: startup
author: DaddyChurchill
commands:
  conurbation:
    description: Sends you to the Conurbation
    usage: /conurbation
    